---
title: UN Environmental Data
homepage: http://geodata.grid.unep.ch/
category: GIS
description:
version:
keywords:
image:
temporal:
spatial:
access_level:
copyrights:
accrual_periodicity:
specification:
data_quality: false
data_dictionary:
language:
license:
publisher:
organization:
issued_time:
sources: []
